import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.

		int TwoChildren = 0;
		int ThreeChildren = 0;
		int FourOrMore= 0;
		int TotalChildren = 0;
//for loop which runs T simulations 
		for(int i = 0; i<T; i++){
			boolean Boy = false;
			boolean Girl = false;
			int counter = 0;
//while loop as used previously to check the gender under the assumed probability and add to count
			while(!(Boy && Girl)) {
				double rnd = generator.nextDouble();
				boolean isBoy = rnd < 0.5;

				if (isBoy){
				Boy = true;
				}else { 
					Girl = true;
				}
				counter++;

				}
			TotalChildren += counter;
//checking to see how many children 
			if (counter==2){
				TwoChildren++;
			} else if (counter==3){
				ThreeChildren++;
			} else{
				FourOrMore++;
			}

		}
//final calculations and outputs 
		double AverageChildren = (double) TotalChildren/T;
		System.out.println("Average: " + AverageChildren + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + TwoChildren);
		System.out.println("Number of families with 3 children: " + ThreeChildren);
		System.out.println("Number of families with 4 or more children: " + FourOrMore);
//comparing number of children to determine mode 
		if(TwoChildren > ThreeChildren && TwoChildren > FourOrMore){
			System.out.println("The most common number of children is 2.");
		} else if (ThreeChildren > TwoChildren && ThreeChildren > FourOrMore){
			System.out.println("The most common number of children is 3.");
		} else{
			System.out.println("The most common number of children is 4 or more.");
		}			
	}
	
} 
	
